### ISSUE TITLE
Add hover text in status dots in backoffice

### ISSUE THREAD

**Issue by grundleborg** [ios-cv/carshare#52]
To explain what the colours mean.

Affects bookings and vehicles at the moment.

**Comment by Scilly-guy** [comment]
Three potential ways to do this:
1: Title text - not considered good practice and requires a wait but simple to implement
2: Simple tailwind - [tailwind play](https://play.tailwindcss.com/2eBipAu8Bt) doesn't work with tailwind we have installed
3: Complex tailwind - [youtube](https://www.youtube.com/watch?v=LphBM0vhB6E) will take longer to implement, IMO produces ugly code.
